### PR TITLE
Feature: Show checkout suggestion when player can check out in 3 darts

### PR DESCRIPTION
**Pull request by bernhardsen**

### CODE REVIEW

**Comment by thordy** [comment]
Great suggestion! Will be a nice addition to the app!

Some minor suggetsions:
- Instead of defining all possible checkouts as strings, I suggest using objects with keys for `value` and `modifier` directly. This would simplify the code, and remove all the string manipulation. It would be similar to how it's done in [the kcapp-bot to determine checkouts](https://github.com/kcapp/bot/blob/master/bot.js#L24-L148)
- It needs to check how many darts you have in hand, because right now if I have `190` and hit a `20`, it gives me suggestion for `T20 T20 D25`, but I only have two darts, so can't complete this checkout.
- Frontend would be good to not always show the white bar (where suggestions show up) but I have no idea how it would be better to do this, so probably fine to just leave it like this and once people start using it we will come up with a better suggestion!

**Comment by bernhardsen** [comment]
Thanks for the feed back. I did the following:
- Generated code instead of processing in client
- This is done deliberatly. As a player, even if I can't finish this visit, I would still like to know what would get me down to a (easy) finish. However, I do believe the strategy might change on some values if you have 2 vs 3 darts. If you have 110 left, currently this would suggest T20, 18, D16. But if you only have 2 darts left, the "correct" way is T20, Bull. 
- I made it static heigh because I didn't want it to push content below it, up and down when hiding/showing it. I agree that it doesn't need to be there all the time. As a compromise, I made it invisible, but still take space when no checkout is available.

**Comment by thordy** [comment]
Looks much better now!
* I think if you adjust so we show `T20` and `D4` etc. instead of just the colors it will be perfect

Regarding the suggestions, my main issue is that lets say you have `170` left. It suggests hitting `T20 T20 D25`. If I throw and hit `T20` I will have `110` left. Now the suggestion will change to `T20 18 D16`, but I only have two darts. If I then throw another `T20` I'm left with `50`, and it will suggest `18 D25` as my checkout. 
This could be very confusing in some areas, so I really think we need to support number of darts. A very easy fix would be to only show it "before" the first dart is thrown, or while you have 3 darts. Then it could be extended in the future to take into account possibilities with 1 or 2 darts etc.

**Comment by bernhardsen** [comment]
I made the changes you suggested.

**Pull request merged**
